# Add DataSpot
set(DATASPOT dataspot)
set(DATASPOT_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/${DATASPOT}/include)
set(DATASPOT_LIBRARY ${DATASPOT})

set(DATASPOT_INCLUDE_DIRS ${DATASPOT_INCLUDE_DIR})
set(DATASPOT_LIBRARIES ${DATASPOT_LIBRARY})

# Check DataSpot
if(NOT TARGET ${DATASPOT})
	add_subdirectory(${CMAKE_SOURCE_DIR}/${DATASPOT})
endif()
