# Add FileSpot
set(FILESPOT filespot)
set(FILESPOT_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/${FILESPOT}/include)
set(FILESPOT_LIBRARY ${FILESPOT})
if(ANDROID)
	set(FILESPOT_LIBRARY ${FILESPOT_LIBRARY} android)
endif()

set(FILESPOT_INCLUDE_DIRS ${FILESPOT_INCLUDE_DIR})
set(FILESPOT_LIBRARIES ${FILESPOT_LIBRARY})

# Check FileSpot
if(NOT TARGET ${FILESPOT})
	add_subdirectory(${CMAKE_SOURCE_DIR}/${FILESPOT})
endif()
