# Add GltfSpot
set(GLTFSPOT gltfspot)
set(GLTFSPOT_INCLUDE_DIR ${MODULE_DIR}/${GLTFSPOT}/include)
set(GLTFSPOT_LIBRARY ${GLTFSPOT})

set(GLTFSPOT_INCLUDE_DIRS ${GLTFSPOT_INCLUDE_DIR})
set(GLTFSPOT_LIBRARIES ${GLTFSPOT_LIBRARY})

# Check GltfSpot
if(NOT TARGET ${GLTFSPOT})
	add_subdirectory(${MODULE_DIR}/${GLTFSPOT})
endif()
